#' Convert all the results of the GA into a data.table
#'
#' @param results_GA list generated by GA run
#'
#' @returns data.table with columns the names of the values
#' @export
convert_resultGA <- function(results_GA) {
  
  # convert the results into a proper format (data.table)
  total_list <- data.table()
  for (iter in 1:length(results_GA)) {
    
    result_iter <- rbindlist(results_GA[[iter]])
    result_iter[, Iteration := iter]
    
    total_list <- rbindlist(list(total_list, 
                                 result_iter))
  }
  
  return(total_list)
}
