install.packages(c("data.table", 
                   "R2DT", 
                   "plyr", 
                   "devFunc", 
                   "mgcv", 
                   "speedglm", 
                   "fastglm", 
                   "caret", 
                   "collapse", 
                   "crayon", 
                   "memoise", 
                   "sigmoid", 
                   "Matrix", 
                   "parallel", 
                   "doParallel"))
install.packages("CASdatasets")

install.packages("devtools")
devtools::install_github("JolienPonnet/fastConcProb")
