library(Matrix)
library(data.table)
library(R2DT)
library(plyr)
library(devFunc)
library(mgcv)
library(fastConcProb)
library(speedglm)
library(fastglm)

library(CASdatasets)

library(memoise) 
library(parallel)
library(doParallel)
